---
- name: Debug message and register overview
  hosts: localhost
  vars:
    var1: hello
  tasks:
    - name: debug message
      debug: msg="A test message"
    - shell: /usr/bin/uptime
      register: var2
    - name: Display register variable
      debug: var=var2

