---
- name: testing the connection types
  hosts: all
  environment:
    GROUPNAME: testservers
  tasks:
    - name: template out hostfile
      template:
        src: template.j2
        dest: /tmp/{{ inventory_hostname }}
