---
- name: testing the async
  hosts: remote
  tasks:
    - name: template script
      template:
        src: templates/longfiles.j2
        dest: /usr/local/bin/longfiles
        owner: root
        group: root
        mode: 0755
    - name: run longfiles script
      command: "/usr/local/bin/longfiles {{ item }} /tmp/{{ item }}.file"
      async: 110
      poll: 0
      with_items:
        - foo
        - bar
        - baz
      register: script_sleeper
    - name: show sccript_sleeper value
      debug:
        var: script_sleeper
    - name: check status of longfiles script
      async_status: "jid={{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      with_items: "{{ script_sleeper.results }}"
