---
- name: Automate instance call
  hosts: cloud
  vars:
    groups_url: "https://10.100.52.241/api/automation_requests"
  tasks:
    - name: Call to CloudForms to execute an automate instance
      uri:
        url: "{{ groups_url }}"
        method: POST
        validate_certs: no
        user: "admin"
        password: "smartvm"
        headers:
           Content-Type: "application/json"
        body: "{\"version\":\"1.1\",\"uri_parts\":{\"namespace\":\"Openstack/Flavors\",\"class\":\"Methods\",\"instance\":\"get_flavors\"},\"requester\":{\"auto_approve\":true}}"
        body_format: json
        return_content: yes
      register: token_output
    - name: Show the requested result
      debug: var=token_output
