---
- name: Automate instance call
  hosts: cloud
  vars:
    groups_url: "https://10.100.52.241/api/automation_requests/1234000000000081"
  tasks:
    - name: Call to CloudForms to execute an automate instance
      uri:
        url: "{{ groups_url }}"
        method: GET
        validate_certs: no
        user: "admin"
        password: "smartvm"
        headers:
           Content-Type: "application/json"
        body_format: json
        return_content: yes
      register: token_output
    - name: Show the requested result
      debug: var=token_output.json.options.return.return
