---
- name: install and start appache
  hosts: remote
  tasks:
    - name: Include the vars file
      include_vars: vars/service_vars.yml
      
    - name: Include the tasks
      include: tasks/packages.yml

     