---
- name: install extra packages
  yum:
    name: "{{extra_packages}}"
- name: Download conf file
  get_url:
    url: # put the conf url here
    dest: "{{configure_database_path}}"
    owner: mysql
    group: mysql
    mode: 0644
    seuser: system_u
    setype: mysqld_etc_t
    force: yes
- name:
  service:
    name: "{{db_service}}"
    state: started
    enabled: true