--- 
- name: demo loops
  hosts: remote
  tasks:
    - name: install packages
      yum:
        name: {{item}}
        state: latest
      with_items:
        - postfix
        - devcot
    - name: start services
      service:
        name: {{item}}
        state: started
        enabled: true
      with_items:
        - postfix
        - devcot
        