---
- name: Error handling
  hosts: remote
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: install {{ web_package}} package
      yum:
        name: "{{web_package}}"
        state: latest
      ignore_errors: yes
    - name: install {{db_package}}
      yum:
        name: "{{db_package}}"
        state: latest