---
- name: install postfix
  yum:
    name: postfix
    state: latest
  tags:
    - server
  notify:
    - start_postfix
- name: install dovecot
  yum:
    name: dovecot
    state: latest
  tags:
    - client
  notify:
    - start_dovecot
- name: Download main.cf cofig for postfix
  get_url:
    url: # put your url here
    dest: /etc/postfix/main.cf
  tags:
    - server
  notify:
    - restart_postfix
    
