---
- name: Error handling
  hosts: remote
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - block:
      - name: check {{web_package}} installation status
        command: yum list installed "{{web_package}}"
        register: command_result

      - name: install {{ web_package}} package
        yum:
          name: "{{web_package}}"
          state: latest
        ignore_errors: yes
      rescue:
        - name: install {{db_package}}
          yum:
            name: "{{db_package}}"
            state: latest
      always:
        - name: start {{ db_service}} 
          service:
            name: "{{db_service}}"
            state: started