---
- name: install remote facts
  hosts: remote
  vars: 
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Create facts.d directory
      file:
        state: directory
        recurse: yes        
        path: "{{ remote_dir }}"

    - name: install the facts file
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
