---
- name: Debug message and register overview
  hosts: localhost
  vars:
    var1: hello
  tasks:
    - name: debug message
      debug: msg="A test message"
    - shell: /usr/bin/uptime
      register: var2
    - name: debug verbosity 1
      debug: var=var2 verbosity=1
    - name: debug verbosity 2
      debug: var=var2 verbosity=2
    - name: debug verbosity 3
      debug: var=var2 verbosity=3
